---@brief
---Following is the default configuration, see |nvim_tree.config| for details.
---
---```lua
---
--- ---@type nvim_tree.config
--- local config = {
--- config-default-injection-placeholder
--- }
---```
