---@meta
error("Cannot require a meta file")

---Use file system watchers (libuv fs_event) to monitor the filesystem for changes and update the tree.
---
---With this feature, the tree will be updated only for the appropriate folder change, resulting in better performance.
---
---Watchers may be disabled for absolute directory paths via {ignore_dirs}. Useful when path is not in `.gitignore` or git integration is disabled.
---
---|vim.regex| strings must be backslash escaped e.g. `"my-proj/\\.build$"`
---
---Using this will disable |BufEnter| and |BufWritePost| events in nvim-tree which were used to update the whole tree.
---@class nvim_tree.Config.FilesystemWatchers
---
---(default: `true`)
---@field enable? boolean
---
---Idle milliseconds between filesystem change and tree update.
---(default: `50`)
---@field debounce_delay? integer
---
---Disable for directories via a list of |vim regex| OR a function passed the absolute path of the directory.
---(default: `{ "/.ccls-cache", "/build", "/node_modules", "/target", }`)
---@field ignore_dirs? string[]|fun(path: string): boolean
