---@meta
error("Cannot require a meta file")



---Use file system watchers (libuv `uv_fs_event_t`) to monitor the filesystem for changes and update the tree.
---
---With this feature, the tree will be partially updated on specific directory changes, resulting in better performance.
---
---Watchers may be disabled for absolute directory paths via {ignore_dirs}.
---This may be useful when a path is not in `.gitignore` or git integration is disabled.
--- - A list of [regular-expression] to match a path, backslash escaped e.g. `"my-proj/\\.build$"` OR
--- - A function that is passed an absolute path and returns `true` to disable
---
---Watchers may be enabled only for specific directories via {whitelist_dirs}. When it is empty (default), watchers are enabled for all directories.
---Uses same semantics as {ignore_dirs} except that the function returns `true` to enable watchers for that path.
---This is strongly recommended for windows: [nvim-tree-os-specific].
---
---After {max_events} consecutive filesystem events on a single directory with an interval < {debounce_delay}:
---- The filesystem watcher will be disabled for that directory.
---- A warning notification will be shown.
---- Consider adding this directory to {ignore_dirs}
---
---@class nvim_tree.config.filesystem_watchers
---
---(default: `true`)
---@field enable? boolean
---
---Idle milliseconds between filesystem change and tree update.
---(default: `50`)
---@field debounce_delay? integer
---
---Disable for specific directories.
---(default: `{ "/.ccls-cache", "/build", "/node_modules", "/target", "/.zig-cache"}`)
---@field ignore_dirs? string[]|(fun(path: string): boolean)
---
---Optionally enable only for specific directories, obeying {ignore_dirs}
---(default: `{}`)
---@field whitelist_dirs? string[]|(fun(path: string): boolean)
---
---Disable for a single directory after {max_events} consecutive events with an interval < {debounce_delay}.
---Set to 0 to allow unlimited consecutive events.
---(default: `0` or `1000` on windows)
---@field max_events? integer
