return {
  setup = require'nvim-tree.actions'.setup,
  close = require'nvim-tree.actions'.close,
  toggle = require'nvim-tree.actions'.toggle,
  redraw = require'nvim-tree.actions'.redraw,
  open = require'nvim-tree.actions'.open,
  open_file = require'nvim-tree.actions'.open_file,
  change_cwd = require'nvim-tree.actions'.change_cwd,
  rename_file = require'nvim-tree.actions'.rename_file,
  add_file = require'nvim-tree.actions'.add_file,
  remove_file = require'nvim-tree.actions'.remove_file,
  copy = require'nvim-tree.actions'.copy,
  cut = require'nvim-tree.actions'.cut,
  paste = require'nvim-tree.actions'.paste,
}
