---@meta
error("Cannot require a meta file")

--
-- Type Aliases for Enums
--

---@alias nvim_tree.PlacementOption "before"|"after"|"signcolumn"|"right_align"
---@alias nvim_tree.HighlightOption "none"|"icon"|"name"|"all"
---@alias nvim_tree.HiddenDisplayOption "none"|"simple"|"all"

--
-- nvim-tree Setup Config
--

---@class nvim_tree.Config
---
---Runs when creating the nvim-tree buffer. Use this to set your nvim-tree specific mappings. See |nvim-tree-mappings|. When `on_attach` is not a function, |nvim-tree-mappings-default| will be called.
---@field on_attach? string|fun(bufnr: integer)
---
---Keeps the cursor on the first letter of the filename when moving in the tree.
---(default: `false`)
---@field hijack_cursor? boolean
---
---Reloads the explorer every time a buffer is written to.
---(default: `true`)
---@field auto_reload_on_write? boolean
---
---Completely disable |netrw|, see |nvim-tree-netrw| for details. It is strongly advised to eagerly disable netrw, due to race conditions at vim startup.
---(default: `false`)
---@field disable_netrw? boolean
---
---Hijack netrw windows, ignored when `disable_netrw` is `true`
---(default: `true`)
---@field hijack_netrw? boolean
---
---Opens in place of the unnamed buffer if it's empty.
---(default: `false`)
---TODO reinstate this one when formatting is done #2934
-----@field hijack_unnamed_buffer_when_opening? boolean
---@field hubwo? boolean
---
---Preferred root directories. Only relevant when |nvim_tree.Config.UpdateFocusedFile| `update_root` is `true`
---@field root_dirs? string[]
---
---Prefer startup root directory when updating root directory of the tree. Only relevant when |nvim_tree.Config.UpdateFocusedFile| `update_root` is `true`
---(default: `false`)
---@field prefer_startup_root? boolean
---
---Changes the tree root directory on |DirChanged| and refreshes the tree.
---(default: `false`)
---@field sync_root_with_cwd? boolean
---
---Automatically reloads the tree on |BufEnter| nvim-tree.
---(default: `false`)
---@field reload_on_bufenter? boolean
---
---Change cwd of nvim-tree to that of new buffer's when opening nvim-tree.
---(default: `false`)
---@field respect_buf_cwd? boolean
---
---Use |vim.ui.select| style prompts. Necessary when using a UI prompt decorator such as dressing.nvim or telescope-ui-select.nvim
---(default: `false`)
---@field select_prompts? boolean
---
---|nvim_tree.Config.Sort|
---@field sort? nvim_tree.Config.Sort
---
---|nvim_tree.Config.View|
---@field view? nvim_tree.Config.View
---
---|nvim_tree.Config.Renderer|
---@field renderer? nvim_tree.Config.Renderer
---
---|nvim_tree.Config.HijackDirectories|
---@field hijack_directories? nvim_tree.Config.HijackDirectories
---
---|nvim_tree.Config.UpdateFocusedFile|
---@field update_focused_file? nvim_tree.Config.UpdateFocusedFile
---
---|nvim_tree.Config.SystemOpen|
---@field system_open? nvim_tree.Config.SystemOpen
---
---|nvim_tree.Config.Git|
---@field git? nvim_tree.Config.Git
---
---|nvim_tree.Config.Diagnostics|
---@field diagnostics? nvim_tree.Config.Diagnostics
---
---|nvim_tree.Config.Modified|
---@field modified? nvim_tree.Config.Modified
---
---|nvim_tree.Config.Filters|
---@field filters? nvim_tree.Config.Filters
---
---|nvim_tree.Config.LiveFilter|
---@field live_filter? nvim_tree.Config.LiveFilter
---
---|nvim_tree.Config.FilesystemWatchers|
---@field filesystem_watchers? nvim_tree.Config.FilesystemWatchers
---
---|nvim_tree.Config.Actions|
---@field actions? nvim_tree.Config.Actions
---
---|nvim_tree.Config.Trash|
---@field trash? nvim_tree.Config.Trash
---
---|nvim_tree.Config.Tab|
---@field tab? nvim_tree.Config.Tab
---
---|nvim_tree.Config.Notify|
---@field notify? nvim_tree.Config.Notify
---
---|nvim_tree.Config.Help|
---@field help? nvim_tree.Config.Help
---
---|nvim_tree.Config.UI|
---@field ui? nvim_tree.Config.UI
---
---|nvim_tree.Config.Log|
---@field log? nvim_tree.Config.Log

--
-- Renderer
--

---@class nvim_tree.Config.Renderer
---@field add_trailing? boolean Appends a trailing slash to folder and symlink folder destination names. Default: `false`
---@field group_empty? boolean|fun(relative_path: string): string Compact folders that only contain a single folder into one node. Boolean or function that takes one argument (the relative path of grouped folders) and returns a string to be displayed. Default: `false`
---@field full_name? boolean Display node whose name length is wider than the width of nvim-tree window in floating window. Default: `false`
---@field root_folder_label? string|boolean|fun(root_cwd: string): string In what format to show root folder. See `:help filename-modifiers` for available `string` options. Set to `false` to hide the root folder.  or `boolean` or `function(root_cwd)`, Default: `":~:s?$?/..?"`
---@field indent_width? integer Number of spaces for an each tree nesting level. Minimum 1. Default: `2`
---@field special_files? string[] A list of filenames that gets highlighted with `NvimTreeSpecialFile`. Default: `{ "Cargo.toml", "Makefile", "README.md", "readme.md", }`
---@field hidden_display? fun(hidden_stats: table<string, integer>): string|nil|nvim_tree.HiddenDisplayOption Show a summary of hidden files below the tree using `NvimTreeHiddenDisplay Default: `"none"`
---@field symlink_destination? boolean Whether to show the destination of the symlink. Default: `true`
---@field decorators? (string|nvim_tree.api.decorator.UserDecorator)[] Highlighting and icons for the nodes, in increasing order of precedence. Uses strings to specify builtin decorators otherwise specify your `nvim_tree.api.decorator.UserDecorator` class. Default: > lua { "Git", "Open", "Hidden", "Modified", "Bookmark", "Diagnostics", "Copied", "Cut", }
---@field highlight_git? nvim_tree.HighlightOption Enable highlight for git attributes using `NvimTreeGit*HL` highlight groups. Requires |nvim-tree.git.enable| Value can be `"none"`, `"icon"`, `"name"` or `"all"`. Default: `"none"` @see nvim-tree.git.enable
---@field highlight_diagnostics? nvim_tree.HighlightOption Enable highlight for diagnostics using `NvimTreeDiagnostic*HL` highlight groups. Requires |nvim-tree.diagnostics.enable| Value can be `"none"`, `"icon"`, `"name"` or `"all"`. Default: `"none"` @see nvim-tree.diagnostics.enable
---@field highlight_opened_files? nvim_tree.HighlightOption Highlight icons and/or names for |bufloaded()| files using the `NvimTreeOpenedHL` highlight group. See |nvim-tree-api.navigate.opened.next()| and |nvim-tree-api.navigate.opened.prev()| Value can be `"none"`, `"icon"`, `"name"` or `"all"`. Default: `"none"`
---@field highlight_modified? nvim_tree.HighlightOption Highlight icons and/or names for modified files using the `NvimTreeModifiedFile` highlight group. Requires |nvim-tree.modified.enable| Value can be `"none"`, `"icon"`, `"name"` or `"all"` Default `"none"` @see nvim-tree.modified.enable
---@field highlight_hidden? nvim_tree.HighlightOption Highlight icons and/or names for hidden files (dotfiles) using the `NvimTreeHiddenFileHL` highlight group. Value can be `"none"`, `"icon"`, `"name"` or `"all"` Default `"none"`
---@field highlight_bookmarks? nvim_tree.HighlightOption Highlight bookmarked using the `NvimTreeBookmarkHL` group. Value can be `"none"`, `"icon"`, `"name"` or `"all"` Default `"none"`
---@field highlight_clipboard? nvim_tree.HighlightOption Enable highlight for clipboard items using the `NvimTreeCutHL` and `NvimTreeCopiedHL` groups. Value can be `"none"`, `"icon"`, `"name"` or `"all"`. Default: `"name"`
---@field indent_markers? nvim_tree.Config.Renderer.IndentMarkers Configuration options for tree indent markers.
---@field icons? nvim_tree.Config.Renderer.Icons Configuration options for icons.

---@class nvim_tree.Config.Renderer.IndentMarkers
---@field enable? boolean Display indent markers when folders are open Default: `false`
---@field inline_arrows? boolean Display folder arrows in the same column as indent marker when using |renderer.icons.show.folder_arrow| Default: `true`
---@field icons? nvim_tree.Config.Renderer.IndentMarkers.Icons Icons shown before the file/directory. Length 1. Default: > lua { corner = "└", edge = "│", item = "│", bottom = "─", none = " ", }

---@class nvim_tree.Config.Renderer.IndentMarkers.Icons
---@field corner? string Default: `"└"`
---@field edge? string Default: `"│"`
---@field item? string Default: `"│"`
---@field bottom? string Default: `"─"`
---@field none? string Default: `" "`

---@class nvim_tree.Config.Renderer.Icons Configuration options for icons.
---@field web_devicons? nvim_tree.Config.Renderer.Icons.WebDevicons Configure optional plugin `"nvim-tree/nvim-web-devicons"`
---@field git_placement? nvim_tree.PlacementOption Git icons placement. Default: `"before"`
---@field diagnostics_placement? nvim_tree.PlacementOption Diganostic icon placement. Default: `"signcolumn"` @see nvim-tree.view.signcolumn @see nvim-tree.renderer.icons.show.diagnostics
---@field modified_placement? nvim_tree.PlacementOption Modified icon placement. Default: `"after"`
---@field hidden_placement? nvim_tree.PlacementOption Hidden icon placement. Default: `"after"`
---@field bookmarks_placement? nvim_tree.PlacementOption Bookmark icon placement. Default: `"signcolumn"` @see nvim-tree.renderer.icons.show.bookmarks
---@field padding? nvim_tree.Config.Renderer.Icons.Padding
---@field symlink_arrow? string Used as a separator between symlinks' source and target. Default: `" ➛ "`
---@field show? nvim_tree.Config.Renderer.Icons.Show Configuration options for showing icon types. Left to right order: file/folder, git, modified, hidden, diagnostics, bookmarked.
---@field glyphs? nvim_tree.Config.Renderer.Icons.Glyphs Configuration options for icon glyphs. NOTE: Do not set any glyphs to more than two characters if it's going to appear in the signcolumn.

---@class nvim_tree.Config.Renderer.Icons.WebDevicons
---@field file? nvim_tree.Config.Renderer.Icons.WebDevicons.File File icons.
---@field folder? nvim_tree.Config.Renderer.Icons.WebDevicons.Folder Folder icons.

---@class nvim_tree.Config.Renderer.Icons.WebDevicons.File
---@field enable? boolean Show icons on files. Overrides |nvim-tree.renderer.icons.glyphs.default| Default: `true`
---@field color? boolean Use icon colors for files. Overrides highlight groups. Default: `true`

---@class nvim_tree.Config.Renderer.Icons.WebDevicons.Folder
---@field enable? boolean Show icons on folders. Overrides |nvim-tree.renderer.icons.glyphs.folder| Default: `false`
---@field color? boolean Use icon colors for folders. Overrides highlight groups. Default: `true`

---@class nvim_tree.Config.Renderer.Icons.Padding
---@field icon? string Inserted between icon and filename. Default: `" "`
---@field folder_arrow? string Inserted between folder arrow icon and file/folder icon. Default: `" "`

---@class nvim_tree.Config.Renderer.Icons.Show
---@field file? boolean Show an icon before the file name. Default: `true`
---@field folder? boolean Show an icon before the folder name. Default: `true`
---@field folder_arrow? boolean Show a small arrow before the folder node. Arrow will be a part of the node when using |renderer.indent_markers|. Default: `true`
---@field git? boolean Show a git status icon, see |renderer.icons.git_placement| Requires |git.enable| `= true` Default: `true` @see nvim-tree.renderer.icons.git_placement @see nvim-tree.git.enable
---@field modified? boolean Show a modified icon, see |renderer.icons.modified_placement| Requires |modified.enable| `= true` Default: `true` @see nvim-tree.renderer.icons.modified_placement @see nvim-tree.modified.enable
---@field hidden? boolean Show a hidden icon, see |renderer.icons.hidden_placement| Default: `false` @see nvim-tree.renderer.icons.hidden_placement
---@field diagnostics? boolean Show a diagnostics status icon, see |renderer.icons.diagnostics_placement| Requires |diagnostics.enable| `= true` Default: `true` @see nvim-tree.renderer.icons.diagnostics_placement @see nvim-tree.diagnostics.enable
---@field bookmarks? boolean Show a bookmark icon, see |renderer.icons.bookmarks_placement| Default: `true` @see nvim-tree.renderer.icons.bookmarks_placement

---@class nvim_tree.Config.Renderer.Icons.Glyphs
---@field default? string Glyph for files. Overridden by |nvim-tree.renderer.icons.web_devicons| if available. Default: `""`
---@field symlink? string Glyph for symlinks to files. Default: `""`
---@field bookmark? string Bookmark icon. Default: `"Ὰ4"`
---@field modified? string Icon to display for modified files. Default: `"●"`
---@field hidden? string Icon to display for hidden files. Default: `"c""`
---@field folder? nvim_tree.Config.Renderer.Icons.Glyphs.Folder Glyphs for directories. Overridden by |nvim-tree.renderer.icons.web_devicons| if available. Default: `{ arrow_closed = "", arrow_open = "", default = "", open = "", empty = "", empty_open = "", symlink = "", symlink_open = "", }`
---@field git? nvim_tree.Config.Renderer.Icons.Glyphs.Git Glyphs for git status. Default: `{ unstaged = "✗", staged = "✓", unmerged = "", renamed = "➜", untracked = "★", deleted = "", ignored = "◌", }`

---@class nvim_tree.Config.Renderer.Icons.Glyphs.Folder
---@field arrow_closed? string Default: `""`
---@field arrow_open? string Default: `""`
---@field default? string Default: `""`
---@field open? string Default: `""`
---@field empty? string Default: `""`
---@field empty_open? string Default: `""`
---@field symlink? string Default: `""`
---@field symlink_open? string Default: `""`

---@class nvim_tree.Config.Renderer.Icons.Glyphs.Git
---@field unstaged? string Default: `"✗"`
---@field staged? string Default: `"✓"`
---@field unmerged? string Default: `""`
---@field renamed? string Default: `"➜"`
---@field untracked? string Default: `"★"`
---@field deleted? string Default: `""`
---@field ignored? string Default: `"◌"`


--
-- View
--

---@class nvim_tree.Config.View
---@field adaptive_size? boolean Resize the window on each draw based on the longest line. Default: `false`
---@field centralize_selection? boolean When entering nvim-tree, reposition the view so that the current node is initially centralized, see |zz|. Default: `false`
---@field side? nvim_tree.PlacementOption Side of the tree. Default: `"left"`
---@field preserve_window_proportions? boolean Preserves window proportions when opening a file. If `false`, the height and width of windows other than nvim-tree will be equalized. Default: `false`
---@field number? boolean Print the line number in front of each line. Default: `false`
---@field relativenumber? boolean Show the line number relative to the line with the cursor in front of each line. Default: `false`
---@field signcolumn? nvim_tree.HiddenDisplayOption Show |signcolumn|. Default: `"yes"`
---@field width? string|integer|nvim_tree.Config.View.Width|fun(): integer|string Width of the window: can be a `%` string, a number representing columns, a function or a table. A table indicates that the view should be dynamically sized based on the longest line. Default: `30`
---@field float? nvim_tree.Config.View.Float Configuration options for floating window.
---@field cursorline? boolean Enable |cursorline| in nvim-tree window. Default: `true`
---@field debounce_delay? integer Idle milliseconds before some reload / refresh operations. Increase if you experience performance issues around screen refresh. Default: `15` (ms)

---@class nvim_tree.Config.View.Width
---@field min? string|integer|fun(): integer|string Minimum dynamic width. Default: `30`
---@field max? string|integer|fun(): integer|string Maximum dynamic width, -1 for unbounded. Default: `-1`
---@field lines_excluded? string[] Exclude these lines when computing width. Supported values: `"root"`. Default: `{ "root" }`
---@field padding? integer|fun(): integer|string Extra padding to the right. Default: `1`

---@class nvim_tree.Config.View.Float
---@field enable? boolean If true, tree window will be floating. Default: `false`
---@field quit_on_focus_loss? boolean Close the floating tree window when it loses focus. Default: `true`
---@field open_win_config? table|fun(): table Floating window config. See |nvim_open_win()| for more details. Default: `{ relative = "editor", border = "rounded", width = 30, height = 30, row = 1, col = 1, }`
